### ISSUE TITLE
Custom Fields are not saving in database

### ISSUE THREAD

**Issue by ikashifullah** [BocianCZ/slider-module#42]
Hi @becquerel,
 Thank you for amazing slider module in Asgardcms.

I am facing some issue when I add custom fields to Slide Entity, I have tried different ways, but couldn't get it to save in database table, slider__slides, Could you please guide how can I do so?

**Comment by becquerel** [comment]
Hi @kashifullahwebdeveloper 

sure, I can point you in the right direction, but it would be helpful to actually see the code. Do you by any chance have a fork on github with the code, so I can take a look what is the problem ?

One potential problem I can think of is to make sure you added your custom fields to the `$fillable` array on either `Slide` or `SlideTranslation` entities. If that does not help, I'd really have to see the code you're having problems with

**Comment by ikashifullah** [comment]
Thank you so much for quick reply.

I am going to fork it and then I will share a link with you, then you can let me know what am I doing wrong!

**Comment by ikashifullah** [comment]
@becquerel ,

I have forked your repo, and made the changes, you can see that I already have $fillable fields as follow:
https://github.com/kashifullahwebdeveloper/slider-module/blob/master/Entities/Slide.php#L37-L44

**Comment by becquerel** [comment]
@kashifullahwebdeveloper it seems that your migrations and forms are mixed up.

You are creating `link_name1-4` and `link_url1-4` on the `slider__slides` table, and `link_name1-4` on your `slider__slide_translations` table

However, in your template, in your `create-links-trans-fields.blade.php`, you are creating form elements for TRANSLATION table, but you are also including all `_url` fields. Remember, that you do not have `url`  fields on translation table - they exist only on the main `slider__slides` table, so this is a problem
`{!! Form::text("{$lang}[link_url1]",`

I'm not sure what your intention with these custom fields is, but you either need to fix the migration and put the missing url columns on the `slider__slide_translations` table (if you want to have these fields based on language), or you need to change the HTML form so it does not contain the `{$lang}` prefix
`{!! Form::text("link_url1",...` (and also probably move it elsewhere, because right now, custom URLs are in the translatable section of the form, repeating for each language)

I tried to disable all custom URLs from the form, left only link names, and slide successfully saved to DB with these custom fields (names)

**Comment by becquerel** [comment]
I'm going to close this issue, as it is really not really related to the original code

**Comment by ikashifullah** [comment]
Thank you, @becquerel it worked!
