### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by aviqbaihaqy** [BocianCZ/slider-module#71]
in asgardcms v3, found error 
![image](https://user-images.githubusercontent.com/1930221/66018394-19184c80-e509-11e9-8f64-4b354f35d07f.png)

**Comment by becquerel** [comment]
@baihaqyaviq thank you for the report ... I actually never tried installing using asgard artisan commands, need to take a look at it.

In the meantime as a workaround, you should be able to simply put the dependency in composer.json and run `composer update`

**Comment by becquerel** [comment]
I think I found the problem. It is more of a bug in Asgard module downloader which does not use actual module name (`Slider`), but tries to get it from the name you put in the command.

This can be fixed by using `php artisan asgard:download:module bociancz/slider`, it should put the module in the correct directory. 

I am going to update readme to reflect this

**Comment by aviqbaihaqy** [comment]
oke thanks for response
